# compile from latest commits

name: 24.10-mtk-default

on:
  workflow_dispatch:
    inputs:
      target:
        description: Choose build target
        required: true
        type: string
        default: 'filogic-mac80211-bpi-r4'
        options:
          - filogic-mac80211-mt7988_rfb-mt7996
          - filogic-mac80211-mozart
          - filogic-mac80211-bpi-r4
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget -y

  checkout_and_build:
    needs: setup
    runs-on: ubuntu-24.04

    # https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/+/refs/heads/master/autobuild/unified/
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Checkout openwrt
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: openwrt-24.10
          path: openwrt

      # external build
      - name: Clone mtk-openwrt-feeds
        run: git clone --branch master https://git01.mediatek.com/openwrt/feeds/mtk-openwrt-feeds mtk-openwrt

      - name: Prepare for building
        run: |
          cd openwrt
          bash ../mtk-openwrt/autobuild/unified/autobuild.sh ${{ inputs.target }} prepare log_file=make

      - name: Delete mtk-openwrt
        run: rm -rf mtk-openwrt

      - name: Build
        run: |
          cd openwrt
          export NO_JEVENTS=1
          make -j`nproc` download world

      - name: Tar output
        run: tar -czvf mtk-openwrt-24.10.tar.gz openwrt/bin/targets/mediatek/filogic

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mtk-openwrt-24.10
          path: mtk-openwrt-24.10.tar.gz

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.target }}
          release_name: "Nightly ${{ env.RELEASE_DATE }}"
          draft: false
          prerelease: true

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mtk-openwrt-24.10.tar.gz
          asset_name: mtk-openwrt-24.10.tar.gz
          asset_content_type: application/gzip
          
