# compile from latest commits

name: 24.10-perpare

on:
  workflow_dispatch:
    inputs:
      release_state:
        description: "Prerelease"
        type: boolean
        required: true
        default: true
      release_tag:
        description: "Release Tag"
        type: string
        required: true
        default: "Nightly"
      openwrt_commit:
        description: "OpenWrt Commit to Use"
        type: string
        required: true
        default: "HEAD"
      mtk_commit:
        description: "MTK Feeds Commit to Use"
        type: string
        required: true
        default: "HEAD"
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
    
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget -y

      # https://git01.mediatek.com/plugins/gitiles/openwrt/feeds/mtk-openwrt-feeds/+/refs/heads/master/autobuild/unified/
      - name: Checkout openwrt
        run: |
          sudo git clone --branch openwrt-24.10 https://github.com/openwrt/openwrt.git /mnt/openwrt
          cd /mnt/openwrt
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            sudo git checkout ${{ inputs.openwrt_commit }}
          fi

      # external build
      - name: Clone mtk-openwrt-feeds
        run: |
          sudo git clone --branch master https://git01.mediatek.com/openwrt/feeds/mtk-openwrt-feeds /mnt/mtk-openwrt
          cd /mnt/mtk-openwrt
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            sudo git checkout ${{ inputs.mtk_commit }}
          fi

      - name: Autobuild prepare
        run: |
          cd /mnt/openwrt
          export FORCE_UNSAFE_CONFIGURE=1
          sudo -E bash ../mtk-openwrt/autobuild/unified/autobuild.sh filogic-mac80211-bpi-r4 prepare log_file=make

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mtk-openwrt-24.10-sauce
          path: /mnt/openwrt
